# Generated by Django 4.2.16 on 2024-12-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
